version: '3'

services:
  linkmart:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'vinci33/jadc28:latest'
    ports:
      - '8080:8080'
    volumes:
      - ./config:/usr/src/app/config
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkmart
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data